services:
  db:
    image: postgres:17.6-alpine
    container_name: postgres-db-camrelay
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      app-network:
        ipv4_address: 192.168.100.2

  turn:
    image: instrumentisto/coturn
    container_name: turn-server
    restart: unless-stopped
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    ports:
      - "9001:9001/udp"
      - "9001:9001/tcp"
      - "49152-49200:49152-49200/udp"
    networks:
      app-network:
        ipv4_address: 192.168.100.3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: camrelay-backend
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "9000"
    networks:
      app-network:
        ipv4_address: 192.168.100.4

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: camrelay-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env.production
    expose:
      - "80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app-network:
        ipv4_address: 192.168.100.5

  nginx:
    image: nginx:latest
    container_name: camrelay-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/nginx/cert.pem:ro
      - ./nginx/cert-key.pem:/etc/nginx/cert-key.pem:ro
    networks:
      app-network:
        ipv4_address: 192.168.100.6

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

volumes:
  db_data:
